---
- name: "Deploy descheduler chart"
  frantchenco.helm_wrapper.install:
    name: "{{ helm_descheduler_name }}"
    chart_repo_url: "{{ helm_descheduler_chart_repo_url }}"
    chart_version: "{{ helm_descheduler_chart_version }}"
    chart_ref: "{{ helm_descheduler_chart_ref }}"
    release_namespace: "{{ helm_descheduler_release_namespace }}"
    create_namespace: "{{ helm_descheduler_create_namespace }}"
    values: "{{ helm_descheduler_values | to_json }}"
    values_files: "{{ helm_descheduler_values_files }}"
    wait: "{{ helm_descheduler_wait }}"
    disable_hook: "{{ helm_descheduler_disable_hook }}"
    force: "{{ helm_descheduler_force }}"
    atomic: "{{ helm_descheduler_atomic }}"
    skip_crds: "{{ helm_descheduler_skip_crds }}"
    update_repo_cache: "{{ helm_descheduler_update_repo_cache }}"
    binary_path: "{{ helm_descheduler_binary_path }}"
    context: "{{ helm_descheduler_context }}"
    kubeconfig: "{{ helm_descheduler_kubeconfig }}"
    validate_certs: "{{ helm_descheduler_validate_certs }}"